### ISSUE TITLE
Footer too low on some pages

### ISSUE THREAD

**Issue by DavidAylaian** [OriginalAndCreativeName/Centennial-Graphics-Site#15]
On some pages (can currently be seen on [404.html](http://chsgraphics.x10host.com/error/404.html) and [403.html](http://chsgraphics.x10host.com/error/403.html)), the footer pushes the page too low and there is an unnecessary scroll.

**Comment by Carl625** [comment]
Fixed 'bug' where the "Forbidden" and "Page not found" text just had a bottom margin that was pushing other elements slightly too far and I just removed it

**Comment by Carl625** [comment]
The margins not the text
